[package]
name = "cryptofiles"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
magic-crypt = "4.0.1"
rand = "0.9.2"

[[bin]]
path = "src/main.rs"
name = "main"

[dev-dependencies]
tempfile = "3.23.0"
